 # ONLY STRING ALL IS POSSIBLE
 
 create or replace table `mldata-8nkm.tw_weather.taichung_201607_202010`(
    `month`	STRING,
    `ObsTime`	STRING,
    `StnPres`	STRING,
    `SeaPres`		STRING,
    `StnPresMax`		STRING,
    `StnPresMaxTime`	STRING,
    `StnPresMaxTimeSec`	STRING,
    `StnPresMin`		STRING,
    `StnPresMinTime`	STRING,
    `StnPresMinTimeSec`	STRING,
    `Temperature`		STRING,
    `T_Max`		STRING,
    `T_Max_Time`	STRING,
    `T_Max_TimeSec`	STRING,
    `T_Min`		STRING,
    `T_Min_Time`	STRING,
    `T_Min_TimeSec`	 STRING,
    `Td_dew_point`	STRING,
    `RH`	STRING,
    `RHMin`	STRING,
    `RHMinTime`	STRING,
    `RHMinTimeSec`	STRING,
    `WS`	STRING,
    `WD`	STRING,
    `WSGust`	STRING,
    `WDGust`	STRING,
    `WgustTime`	STRING,
    `WgustTimeSec`	STRING,
    `Precp`	STRING,
    `PrecpHour` STRING,
    `PrecpMax10`	STRING,
    `PrecpMax10Time`	STRING,
    `PrecpMax10TimeSec`	STRING,
    `PrecpMax60`	STRING,
    `PrecpMax60Time`	 STRING,
    `PrecpMax60TimeSec`	STRING,
    `SunShine`	STRING,
    `SunShineRate`	STRING,
    `GloblRad`	STRING,
    `VisbMean`	STRING,
    `EvapA`	 STRING,
    `UVIMax`	STRING,
    `UVIMaxTime`	STRING,
    `CloudAmount`		STRING
 );
